version: 2
jobs:
  checkout_code:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          command: |
            apt-get update && apt-get install -y curl && curl -fsSL https://raw.githubusercontent.com/gufranco/dotfiles/master/install.sh | bash
