version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Update apt
          command: apt-get update
      - run:
          name: Install curl
          command: apt-get install curl
      - run:
          name: Install dotfiles
          command: curl -fsSL https://raw.githubusercontent.com/gufranco/dotfiles/master/install.sh | bash
